import type { Question } from '../../types';

export const insurancePaymentReadinessQuestions: Question[] = [
  {
    question_id: 'qb.universal.insurance.has_insurance_v1',
    question_version: '1.0.0',
    tier: 1,
    answer_type: 'single_select',
    selection_cardinality: 'exactly_one',
    requiredness: 'required_to_continue',
    answer_role: 'operational',
    intent_of_answer_set: 'clinical_history',
    entity_kind: 'single_value',
    atom_kind: 'operational',
    downstream_effect: 'personalization',
    render_when: null,
    prompt: 'Do you have health insurance?',
    choices: [
      { value: 'yes_commercial', label: 'Yes (commercial / employer)' },
      { value: 'yes_medicare_medicaid', label: 'Yes (Medicare / Medicaid)' },
      { value: 'no', label: 'No / uninsured' },
      { value: 'unsure', label: "I'm not sure" },
    ],
    emissions: [{ target: 'patient_column', payload: { column: 'has_insurance', value: null } }],
  },
  {
    question_id: 'qb.universal.insurance.carrier_v1',
    question_version: '1.0.0',
    tier: 2,
    answer_type: 'text',
    requiredness: 'conditionally_required',
    answer_role: 'operational',
    intent_of_answer_set: 'clinical_history',
    entity_kind: 'single_value',
    atom_kind: 'operational',
    downstream_effect: 'personalization',
    render_when: { kind: 'response', question_id: 'qb.universal.insurance.has_insurance_v1', operator: 'equals', value: 'yes_commercial' },
    prompt: 'Which insurance company?',
    emissions: [{ target: 'patient_column', payload: { column: 'insurance_carrier', value: null } }],
  },
  {
    question_id: 'qb.universal.insurance.self_pay_willingness_v1',
    question_version: '1.0.0',
    tier: 2,
    answer_type: 'single_select',
    selection_cardinality: 'exactly_one',
    requiredness: 'required_to_continue',
    answer_role: 'commercial_confidence',
    intent_of_answer_set: 'conversion_support',
    entity_kind: 'single_value',
    atom_kind: 'operational',
    downstream_effect: 'personalization',
    render_when: null,
    prompt: "If your insurance doesn't cover treatment, are you willing to self-pay?",
    helper: 'Most weight loss medications are self-pay. Plans typically start around $199/month.',
    choices: [
      { value: 'yes', label: 'Yes' },
      { value: 'maybe_cost_dependent', label: 'Maybe (depends on cost)' },
      { value: 'no', label: 'No' },
    ],
    emissions: [{ target: 'patient_column', payload: { column: 'self_pay_willingness', value: null } }],
  },
];
