import type { Question } from '../../types';

export const profileHardCommitQuestions: Question[] = [
  { question_id: 'qb.universal.profile.legal_first_name_v1', question_version: '1.0.0', tier: 1, answer_type: 'text', requiredness: 'required_to_continue', answer_role: 'operational', intent_of_answer_set: 'forced_classification', entity_kind: 'single_value', atom_kind: 'identity', downstream_effect: 'personalization', render_when: null, prompt: 'Legal first name', emissions: [{ target: 'patient_column', payload: { column: 'legal_first_name', value: null } }] },
  { question_id: 'qb.universal.profile.legal_last_name_v1', question_version: '1.0.0', tier: 1, answer_type: 'text', requiredness: 'required_to_continue', answer_role: 'operational', intent_of_answer_set: 'forced_classification', entity_kind: 'single_value', atom_kind: 'identity', downstream_effect: 'personalization', render_when: null, prompt: 'Legal last name', emissions: [{ target: 'patient_column', payload: { column: 'legal_last_name', value: null } }] },
  { question_id: 'qb.universal.profile.shipping_address_v1', question_version: '1.0.0', tier: 1, answer_type: 'text', requiredness: 'required_to_continue', answer_role: 'operational', intent_of_answer_set: 'forced_classification', entity_kind: 'composite', atom_kind: 'operational', downstream_effect: 'personalization', render_when: null, prompt: 'Shipping address', emissions: [{ target: 'patient_address', payload: { street: '', city: '', state: '', zip: '', country: 'US' } }] },
  { question_id: 'qb.universal.profile.phone_mobile_v1', question_version: '1.0.0', tier: 1, answer_type: 'text', requiredness: 'required_to_continue', answer_role: 'operational', intent_of_answer_set: 'forced_classification', entity_kind: 'single_value', atom_kind: 'identity', downstream_effect: 'personalization', render_when: null, prompt: 'Mobile phone', helper: "We'll text order updates and treatment info.", emissions: [{ target: 'patient_contact', payload: { kind: 'phone_mobile', value: '' } }] },
  { question_id: 'qb.universal.profile.sms_promotional_opt_in_v1', question_version: '1.0.0', tier: 2, answer_type: 'acknowledgment', requiredness: 'optional', answer_role: 'preference', intent_of_answer_set: 'preference_capture', entity_kind: 'single_value', atom_kind: 'consent', downstream_effect: 'personalization', render_when: null, prompt: "I'd also like to receive occasional promotions via text. Opt out anytime.", emissions: [{ target: 'consent', payload: { type: 'marketing_sms', version_hash: '', legal_text_snapshot_id: '', source_surface: 'intake_account_creation', captured_by: 'patient' } }] },
];
