import type { FormDefinition } from '@/lib/forms/types'

export const glp1IntakeForm: FormDefinition = {
  key: 'glp1-intake',
  title: 'Clinical intake',
  steps: [
    {
      title: 'Care goals',
      fields: [
        {
          name: 'primary_pathway',
          label: 'What are you primarily seeking help with?',
          type: 'radio',
          required: true,
          options: [
            { value: 'weight_loss', label: 'Weight loss / metabolic health' },
            { value: 'ed', label: 'Erectile dysfunction' },
            { value: 'hair', label: 'Hair restoration' },
            { value: 'hormone_peptide', label: 'Hormone / peptide support' },
            { value: 'general_wellness', label: 'General wellness / longevity' },
          ],
          colSpan: 'full',
        },
        {
          name: 'secondary_goals',
          label: 'Any secondary goals? (optional)',
          type: 'chips',
          required: false,
          options: [
            { value: 'energy', label: 'Energy' },
            { value: 'sleep', label: 'Sleep' },
            { value: 'libido', label: 'Libido' },
            { value: 'body_composition', label: 'Body composition' },
            { value: 'focus', label: 'Focus' },
            { value: 'joint_recovery', label: 'Joint recovery' },
          ],
          colSpan: 'full',
        },
        {
          name: 'goals_summary',
          label: 'Tell us what you are looking to achieve',
          type: 'textarea',
          required: true,
          rows: 4,
          autoCapitalize: 'sentences',
          placeholder: 'Describe your goals in your own words...',
          colSpan: 'full',
        },
      ],
    },
    {
      title: 'Contact + demographics',
      layout: 'two-column',
      fields: [
        {
          name: 'first_name',
          label: 'First name',
          type: 'text',
          required: true,
          placeholder: 'First name',
          autoComplete: 'given-name',
        },
        {
          name: 'last_name',
          label: 'Last name',
          type: 'text',
          required: true,
          placeholder: 'Last name',
          autoComplete: 'family-name',
        },
        {
          name: 'email',
          label: 'Email',
          type: 'email',
          required: true,
          placeholder: 'you@example.com',
          autoComplete: 'email',
          colSpan: 'full',
        },
        {
          name: 'phone',
          label: 'Mobile phone',
          type: 'tel',
          required: true,
          placeholder: '(248) 231-5689',
          maxLength: 10,
          autoComplete: 'tel',
          inputMode: 'tel',
          colSpan: 'full',
        },
        {
          name: 'dob',
          label: 'Date of birth',
          type: 'text',
          required: true,
          placeholder: 'mm/dd/yyyy',
          maxLength: 10,
          autoComplete: 'bday',
          inputMode: 'numeric',
          colSpan: 'full',
        },
        {
          name: 'sex_assigned_at_birth',
          label: 'Sex assigned at birth',
          type: 'radio',
          required: true,
          options: [
            { value: 'female', label: 'Female' },
            { value: 'male', label: 'Male' },
          ],
          colSpan: 'full',
        },
        {
          name: 'gender_identity',
          label: 'Gender identity (optional)',
          type: 'select',
          required: false,
          options: [
            { value: 'female', label: 'Female' },
            { value: 'male', label: 'Male' },
            { value: 'non_binary', label: 'Non-binary' },
            { value: 'self_describe', label: 'Prefer to self-describe' },
            { value: 'prefer_not_to_say', label: 'Prefer not to say' },
          ],
          colSpan: 'full',
        },
        {
          name: 'height_in',
          label: 'Height (inches)',
          type: 'number',
          required: true,
          min: 48,
          max: 90,
          placeholder: 'e.g. 69',
        },
        {
          name: 'weight_lb',
          label: 'Weight (lbs)',
          type: 'number',
          required: true,
          min: 70,
          max: 700,
          placeholder: 'e.g. 214',
        },
      ],
    },
    {
      title: 'Address',
      layout: 'two-column',
      fields: [
        {
          name: 'address_line1',
          label: 'Street address',
          type: 'text',
          required: true,
          placeholder: '123 Main St',
          autoComplete: 'address-line1',
          colSpan: 'full',
        },
        {
          name: 'address_line2',
          label: 'Apt / suite (optional)',
          type: 'text',
          required: false,
          placeholder: 'Apt 4',
          autoComplete: 'address-line2',
          colSpan: 'full',
        },
        {
          name: 'city',
          label: 'City',
          type: 'text',
          required: true,
          placeholder: 'City',
          autoComplete: 'address-level2',
        },
        {
          name: 'state',
          label: 'State',
          type: 'text',
          required: true,
          placeholder: 'CA',
          maxLength: 2,
          autoComplete: 'address-level1',
        },
        {
          name: 'postal_code',
          label: 'ZIP code',
          type: 'text',
          required: true,
          placeholder: '12345 or 12345-6789',
          maxLength: 10,
          autoComplete: 'postal-code',
          inputMode: 'numeric',
          colSpan: 'full',
        },
      ],
    },
    {
      title: 'Medical history',
      fields: [
        {
          name: 'medical_history_conditions',
          label: 'Select any medical history that applies',
          type: 'chips',
          required: true,
          options: [
            { value: 'none', label: 'None known' },
            { value: 'htn', label: 'HTN' },
            { value: 'diabetes', label: 'Diabetes' },
            { value: 'chf', label: 'CHF' },
            { value: 'ckd', label: 'CKD' },
            { value: 'copd', label: 'COPD / asthma' },
            { value: 'thyroid_disease', label: 'Thyroid disease' },
            { value: 'ed', label: 'Erectile dysfunction' },
            { value: 'osa', label: 'Sleep apnea' },
            { value: 'gout', label: 'Gout' },
            { value: 'gerd', label: 'GERD / reflux' },
            { value: 'other', label: 'Other' },
          ],
          colSpan: 'full',
        },
        {
          name: 'medical_history_notes',
          label: 'Other medical history details',
          type: 'textarea',
          required: false,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Anything else we should know medically...',
          visibleWhen: {
            conditions: [{ field: 'medical_history_conditions', operator: 'includes', value: 'other' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_glp1_use',
          label: 'Have you used GLP-1 medications before?',
          type: 'radio',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          visibleWhen: {
            conditions: [{ field: 'primary_pathway', operator: 'equals', value: 'weight_loss' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_glp1_medications',
          label: 'Which GLP-1 medications have you tried?',
          type: 'chips',
          required: true,
          options: [
            { value: 'semaglutide', label: 'Semaglutide' },
            { value: 'tirzepatide', label: 'Tirzepatide' },
            { value: 'liraglutide', label: 'Liraglutide' },
            { value: 'other', label: 'Other' },
          ],
          visibleWhen: {
            conditions: [{ field: 'prior_glp1_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_glp1_timeline',
          label: 'How long ago and for how long?',
          type: 'text',
          required: true,
          autoCapitalize: 'sentences',
          placeholder: 'e.g. Started 8 months ago, used for 4 months',
          visibleWhen: {
            conditions: [{ field: 'prior_glp1_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_glp1_outcome',
          label: 'Was it successful? Any side effects or issues?',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          visibleWhen: {
            conditions: [{ field: 'prior_glp1_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_ed_use',
          label: 'Have you used ED medications before?',
          type: 'radio',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          visibleWhen: {
            conditions: [{ field: 'primary_pathway', operator: 'equals', value: 'ed' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_ed_medications',
          label: 'Which medications have you used?',
          type: 'chips',
          required: true,
          options: [
            { value: 'sildenafil', label: 'Sildenafil' },
            { value: 'tadalafil', label: 'Tadalafil' },
            { value: 'vardenafil', label: 'Vardenafil' },
            { value: 'avanafil', label: 'Avanafil' },
            { value: 'other', label: 'Other' },
          ],
          visibleWhen: {
            conditions: [{ field: 'prior_ed_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_ed_outcome',
          label: 'How did those medications work for you?',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          visibleWhen: {
            conditions: [{ field: 'prior_ed_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_peptide_use',
          label: 'Have you used peptides/hormone therapies before?',
          type: 'radio',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          visibleWhen: {
            match: 'any',
            conditions: [
              { field: 'primary_pathway', operator: 'equals', value: 'hormone_peptide' },
              { field: 'primary_pathway', operator: 'equals', value: 'general_wellness' },
            ],
          },
          colSpan: 'full',
        },
        {
          name: 'prior_peptide_details',
          label: 'Which therapies, when, and were you comfortable with protocol/dosing?',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          visibleWhen: {
            conditions: [{ field: 'prior_peptide_use', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
      ],
    },
    {
      title: 'Surgical and procedure history',
      fields: [
        {
          name: 'surgical_history_items',
          label: 'Select prior surgeries/procedures',
          type: 'chips',
          required: false,
          options: [
            { value: 'none', label: 'None' },
            { value: 'gallbladder', label: 'Gallbladder surgery' },
            { value: 'colon_surgery', label: 'Colon surgery' },
            { value: 'egd', label: 'EGD' },
            { value: 'colonoscopy', label: 'Colonoscopy' },
            { value: 'bariatric', label: 'Bariatric surgery' },
            { value: 'thyroid_surgery', label: 'Thyroid surgery' },
            { value: 'other', label: 'Other' },
          ],
          colSpan: 'full',
        },
        {
          name: 'surgical_history_notes',
          label: 'Surgical/procedure details',
          type: 'textarea',
          required: false,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Include dates or outcomes if relevant...',
          colSpan: 'full',
        },
      ],
    },
    {
      title: 'Social history',
      layout: 'two-column',
      fields: [
        {
          name: 'tobacco_use',
          label: 'Smoking/vaping',
          type: 'select',
          required: true,
          options: [
            { value: 'never', label: 'Never' },
            { value: 'former', label: 'Former' },
            { value: 'current', label: 'Current' },
          ],
        },
        {
          name: 'alcohol_use',
          label: 'Alcohol',
          type: 'select',
          required: true,
          options: [
            { value: 'none', label: 'None' },
            { value: 'occasional', label: 'Occasional' },
            { value: 'regular', label: 'Regular' },
            { value: 'heavy', label: 'Heavy' },
          ],
        },
        {
          name: 'marijuana_use',
          label: 'Marijuana',
          type: 'select',
          required: true,
          options: [
            { value: 'none', label: 'None' },
            { value: 'occasional', label: 'Occasional' },
            { value: 'regular', label: 'Regular' },
          ],
        },
        {
          name: 'illicit_drug_use',
          label: 'Illicit drugs',
          type: 'select',
          required: true,
          options: [
            { value: 'none', label: 'None' },
            { value: 'past', label: 'Past use' },
            { value: 'current', label: 'Current use' },
          ],
        },
      ],
    },
    {
      title: 'Allergies, medications, supplements',
      fields: [
        {
          name: 'allergies',
          label: 'Allergies (medications, food, environmental)',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Write "none known" if none.',
          colSpan: 'full',
        },
        {
          name: 'current_medications',
          label: 'Current medications',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Name, dose, frequency. Write "none" if none.',
          colSpan: 'full',
        },
        {
          name: 'current_supplements',
          label: 'Current supplements',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Name and frequency. Write "none" if none.',
          colSpan: 'full',
        },
        {
          name: 'family_history',
          label: 'Family history (optional)',
          type: 'textarea',
          required: false,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Notable family medical history (heart disease, diabetes, thyroid, cancers, etc.)',
          colSpan: 'full',
        },
      ],
    },
    {
      title: 'Labs and final concerns',
      fields: [
        {
          name: 'have_labs_or_docs',
          label: 'Do you have labs or documents to share?',
          type: 'radio',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          colSpan: 'full',
        },
        {
          name: 'labs_docs_note',
          label: 'What labs/documents do you have?',
          type: 'textarea',
          required: true,
          rows: 3,
          autoCapitalize: 'sentences',
          placeholder: 'Example: CBC/CMP from Jan 2026, thyroid panel screenshot, lipid panel PDF.',
          visibleWhen: {
            conditions: [{ field: 'have_labs_or_docs', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'labs_attachments',
          label: 'Upload labs/documents/screenshots (optional)',
          description: 'Accepted: PDF, JPG, PNG, WEBP. Up to 10 files.',
          type: 'file',
          required: false,
          multiple: true,
          accept: '.pdf,.jpg,.jpeg,.png,.webp',
          visibleWhen: {
            conditions: [{ field: 'have_labs_or_docs', operator: 'equals', value: 'yes' }],
          },
          colSpan: 'full',
        },
        {
          name: 'questions_or_concerns',
          label: 'Any questions or concerns we should know before your visit?',
          type: 'textarea',
          required: false,
          rows: 4,
          autoCapitalize: 'sentences',
          colSpan: 'full',
        },
      ],
    },
  ],
}
